# Generated by Django 5.2.5 on 2025-09-03 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('key', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Decision Table',
                'verbose_name_plural': 'Decision Tables',
                'db_table': 'decision_table',
                'indexes': [models.Index(fields=['client_code', 'key'], name='decision_ta_client__93571f_idx'), models.Index(fields=['is_active'], name='decision_ta_is_acti_6f6a30_idx')],
                'unique_together': {('client_code', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DecisionTableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('definition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='WorkflowRules.decisiontable')),
            ],
            options={
                'db_table': 'decision_table_version',
                'ordering': ['table', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RuleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('input_ctx', models.JSONField(default=dict)),
                ('expected_output', models.JSONField(default=dict)),
                ('last_run_ok', models.BooleanField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='WorkflowRules.decisiontableversion')),
            ],
            options={
                'verbose_name': 'Rule Test Case',
                'verbose_name_plural': 'Rule Test Cases',
                'db_table': 'rule_test_case',
            },
        ),
        migrations.AddIndex(
            model_name='decisiontableversion',
            index=models.Index(fields=['status', 'valid_from', 'valid_to'], name='decision_ta_status_2435d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisiontableversion',
            unique_together={('table', 'version')},
        ),
    ]
