# Generated by Django 5.2.5 on 2025-08-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHeader',
            fields=[
                ('client', models.CharField(max_length=3)),
                ('internal_class_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_type', models.CharField(max_length=3)),
                ('class_number', models.CharField(max_length=18)),
                ('class_status', models.CharField(blank=True, max_length=1, null=True)),
                ('class_group', models.CharField(blank=True, max_length=10, null=True)),
                ('characteristics_table', models.CharField(blank=True, max_length=20, null=True)),
                ('usage_in_superior_classes', models.CharField(blank=True, max_length=1, null=True)),
                ('multiple_selection_allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Class Header',
                'verbose_name_plural': 'Class Headers',
                'db_table': 'class_header',
            },
        ),
        migrations.CreateModel(
            name='ObjectLink',
            fields=[
                ('client', models.CharField(max_length=3)),
                ('config_object', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('material_number', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'Object Link',
                'verbose_name_plural': 'Object Links',
                'db_table': 'object_link',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('client', models.CharField(max_length=3)),
                ('internal_characteristic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('archive_counter', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('data_type', models.CharField(max_length=4)),
                ('character_length', models.PositiveSmallIntegerField()),
                ('case_sensitive', models.BooleanField(default=False)),
                ('entry_required', models.BooleanField(default=False)),
                ('single_value', models.BooleanField(default=False)),
                ('multilingual', models.BooleanField(default=False)),
                ('display_allowed_values', models.CharField(max_length=1)),
                ('display_assigned_values', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
                'db_table': 'characteristic',
                'unique_together': {('internal_characteristic', 'archive_counter')},
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=3)),
                ('value_counter', models.CharField(max_length=4)),
                ('archive_counter', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=30)),
                ('internal_characteristic', models.ForeignKey(db_column='internal_characteristic', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Classification.characteristic')),
            ],
            options={
                'verbose_name': 'Characteristic Value',
                'verbose_name_plural': 'Characteristic Values',
                'db_table': 'characteristic_value',
                'unique_together': {('internal_characteristic', 'value_counter', 'archive_counter')},
            },
        ),
        migrations.CreateModel(
            name='ClassCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=3)),
                ('item_number', models.CharField(max_length=3)),
                ('archive_counter', models.CharField(max_length=4)),
                ('object_dependent_char', models.CharField(max_length=10)),
                ('characteristic', models.ForeignKey(db_column='characteristic_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='Classification.characteristic')),
                ('class_header', models.ForeignKey(db_column='class_internal_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_characteristics', to='Classification.classheader')),
            ],
            options={
                'verbose_name': 'Class Characteristic',
                'verbose_name_plural': 'Class Characteristics',
                'db_table': 'class_characteristic',
            },
        ),
        migrations.CreateModel(
            name='ClassificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=3)),
                ('object_key', models.CharField(max_length=50)),
                ('value_counter', models.CharField(max_length=3)),
                ('object_class_indicator', models.CharField(max_length=1)),
                ('class_type', models.CharField(max_length=3)),
                ('archive_counter', models.CharField(max_length=4)),
                ('characteristic_value', models.CharField(max_length=30)),
                ('characteristic', models.ForeignKey(db_column='characteristic_id', on_delete=django.db.models.deletion.CASCADE, related_name='classification_values', to='Classification.characteristic')),
            ],
            options={
                'verbose_name': 'Classification Value',
                'verbose_name_plural': 'Classification Values',
                'db_table': 'classification_value',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValueText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=3)),
                ('counter', models.CharField(max_length=4)),
                ('language', models.CharField(max_length=1)),
                ('archive_counter', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=30)),
                ('characteristic_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='Classification.characteristicvalue')),
            ],
            options={
                'verbose_name': 'Characteristic Value Text',
                'verbose_name_plural': 'Characteristic Value Texts',
                'db_table': 'characteristic_value_text',
                'unique_together': {('characteristic_value', 'counter', 'language')},
            },
        ),
    ]
