# Generated by Django 5.2.5 on 2025-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classheader',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classificationvalue',
            name='characteristic_value',
            field=models.CharField(max_length=30),
        ),
    ]
