# Generated by Django 5.2.5 on 2025-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='internal_characteristic',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
