# Generated by Django 5.2.5 on 2025-09-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcreationrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('UNDER_REVIEW_Global_Team', 'Global Data Review'), ('UNDER_REVIEW_Local_Team', 'Local Data Review'), ('UNDER_REVIEW_Tax', 'Tax Team Review'), ('UNDER_REVIEW_Accounting', 'Accounting Review'), ('UNDER_REVIEW_QA', 'QA Review'), ('UNDER_REVIEW_FIN', 'Finance Review'), ('REJECTED', 'Rejected (back to requester)'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=40),
        ),
    ]
