# Generated by Django 5.2.5 on 2025-08-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=18, unique=True)),
                ('deletion_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('material_type', models.CharField(max_length=4)),
                ('industry_sector', models.CharField(max_length=1)),
                ('material_group', models.CharField(max_length=9)),
                ('base_unit_of_measure', models.CharField(max_length=3)),
                ('purchase_order_uom', models.CharField(blank=True, max_length=3, null=True)),
                ('purchasing_value_key', models.CharField(blank=True, max_length=4, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=3, null=True)),
                ('division', models.CharField(blank=True, max_length=2, null=True)),
                ('packaging_material_group', models.CharField(blank=True, max_length=4, null=True)),
                ('authorization_group', models.CharField(blank=True, max_length=4, null=True)),
                ('qm_in_procurement', models.BooleanField(default=False)),
                ('cross_plant_status', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Material',
                'verbose_name_plural': 'Global Materials',
                'db_table': 'global_material',
            },
        ),
        migrations.CreateModel(
            name='MaterialDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=40)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='MaterialGlobal.globalmaterial')),
            ],
            options={
                'verbose_name': 'Material Description',
                'verbose_name_plural': 'Material Descriptions',
                'db_table': 'material_description',
                'unique_together': {('material', 'language')},
            },
        ),
    ]
