# Generated by Django 5.2.5 on 2026-02-23 00:00

from django.db import migrations, models


def seed_sap_check_table_entries(apps, schema_editor):
    SapCheckTableEntry = apps.get_model('MaterialGlobal', 'SapCheckTableEntry')

    rows = [
        ('material_type', 'ROH', 'Raw Material', 10),
        ('material_type', 'HALB', 'Semi-Finished Product', 20),
        ('material_type', 'FERT', 'Finished Product', 30),
        ('material_type', 'HAWA', 'Trading Goods', 40),
        ('industry_sector', 'M', 'Mechanical Engineering', 10),
        ('industry_sector', 'A', 'Retail', 20),
        ('industry_sector', 'P', 'Pharma', 30),
        ('product_hierarchy', '001', 'Corporate Level 001', 10),
        ('product_hierarchy', '001001', 'Subgroup 001001', 20),
        ('product_hierarchy', '001001001', 'Family 001001001', 30),
        ('base_unit_of_measure', 'EA', 'Each', 10),
        ('base_unit_of_measure', 'KG', 'Kilogram', 20),
        ('base_unit_of_measure', 'L', 'Liter', 30),
        ('unit_of_measure', 'EA', 'Each', 10),
        ('unit_of_measure', 'KG', 'Kilogram', 20),
        ('unit_of_measure', 'G', 'Gram', 30),
        ('unit_of_measure', 'L', 'Liter', 40),
        ('weight_unit', 'KG', 'Kilogram', 10),
        ('weight_unit', 'G', 'Gram', 20),
        ('weight_unit', 'LB', 'Pound', 30),
        ('mrp_group', '0001', 'Default Planning Group', 10),
        ('mrp_group', '0002', 'High Rotation', 20),
        ('mrp_group', 'Z001', 'Project Materials', 30),
    ]

    for domain, code, description, sort_order in rows:
        SapCheckTableEntry.objects.update_or_create(
            domain=domain,
            code=code,
            defaults={
                'description': description,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


def unseed_sap_check_table_entries(apps, schema_editor):
    SapCheckTableEntry = apps.get_model('MaterialGlobal', 'SapCheckTableEntry')
    SapCheckTableEntry.objects.filter(
        domain__in=[
            'material_type',
            'industry_sector',
            'product_hierarchy',
            'base_unit_of_measure',
            'unit_of_measure',
            'weight_unit',
            'mrp_group',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialGlobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapCheckTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP Check Table Entry',
                'verbose_name_plural': 'SAP Check Table Entries',
                'db_table': 'sap_check_table_entry',
                'unique_together': {('domain', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='sapchecktableentry',
            index=models.Index(fields=['domain', 'is_active'], name='sap_check_t_domain_4520b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sapchecktableentry',
            index=models.Index(fields=['domain', 'sort_order'], name='sap_check_t_domain_e8d85e_idx'),
        ),
        migrations.RunPython(seed_sap_check_table_entries, unseed_sap_check_table_entries),
    ]
